In [50]:
import pandas as pd
import numpy as np

# 12.1 Selecting Best Models Using Exhaustive Search

In [51]:
# import dataset
df=pd.read_csv('diabetes.csv')
df.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [52]:
df.isna().sum().sum()

0

In [53]:
df.shape

(768, 9)

In [54]:
features = np.array(df[['Pregnancies', 'Glucose', 'BloodPressure', 'SkinThickness', 
                        'Insulin', 'BMI', 'DiabetesPedigreeFunction', 'Age']])
features

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [55]:
target = np.array(df[['Outcome']])
target

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [56]:
# Use scikit-learn’s GridSearchCV:
# Load libraries
import numpy as np
from sklearn import linear_model
from sklearn.model_selection import GridSearchCV

In [57]:
# Create logistic regression
logistic = linear_model.LogisticRegression(max_iter=100000)

In [58]:
# Create range of candidate penalty hyperparameter values
penalty = ['l1', 'l2']

In [59]:
# Create range of candidate regularization hyperparameter values
C = np.logspace(0, 4, 10)

In [60]:
# Create dictionary hyperparameter candidates
hyperparameters = dict(C=C, penalty=penalty)

In [61]:
# Create grid search
gridsearch = GridSearchCV(logistic, hyperparameters, cv=5, verbose=0)

In [62]:
# Fit grid search
best_model = gridsearch.fit(features, target)

c:\python38\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\python38\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\python38\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\python38\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y,

In [63]:
np.logspace(0, 4, 10)

array([1.00000000e+00, 2.78255940e+00, 7.74263683e+00, 2.15443469e+01,
       5.99484250e+01, 1.66810054e+02, 4.64158883e+02, 1.29154967e+03,
       3.59381366e+03, 1.00000000e+04])

In [64]:
# View best hyperparameters
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 1.0


In [65]:
# Predict target vector
best_model.predict(features)

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 1, 0,
       1, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 0, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 0, 0, 1, 0, 0, 0, 0, 1,

# 12.2 Selecting Best Models Using Randomized Search

In [66]:
# Load libraries
from scipy.stats import uniform
from sklearn import linear_model, datasets
from sklearn.model_selection import RandomizedSearchCV

In [67]:
df.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [68]:
features

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [69]:
target

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [70]:
# Create logistic regression
logistic = linear_model.LogisticRegression()

In [71]:
# Create range of candidate regularization penalty hyperparameter values
penalty = ['l1', 'l2']

In [72]:
# Create distribution of candidate regularization hyperparameter values
C = uniform(loc=0, scale=4)

In [73]:
# Create hyperparameter options
hyperparameters = dict(C=C, penalty=penalty)

In [74]:
# Create randomized search
randomizedsearch = RandomizedSearchCV(
    logistic, hyperparameters, random_state=1, n_iter=100, cv=5, verbose=0,
    n_jobs=-1)

In [75]:
# Fit randomized search
best_model = randomizedsearch.fit(features, target)

c:\python38\lib\site-packages\sklearn\model_selection\_validation.py:378: FitFailedWarning: 
230 fits failed out of a total of 500.
The score on these train-test partitions for these parameters will be set to nan.
If these failures are not expected, you can try to debug them by setting error_score='raise'.

Below are more details about the failures:
--------------------------------------------------------------------------------
230 fits failed with the following error:
Traceback (most recent call last):
  File "c:\python38\lib\site-packages\sklearn\model_selection\_validation.py", line 686, in _fit_and_score
    estimator.fit(X_train, y_train, **fit_params)
  File "c:\python38\lib\site-packages\sklearn\linear_model\_logistic.py", line 1091, in fit
    solver = _check_solver(self.solver, self.penalty, self.dual)
  File "c:\python38\lib\site-packages\sklearn\linear_model\_logistic.py", line 61, in _check_solver
    raise ValueError(
ValueError: Solver lbfgs supports only 'l2' or 'none' 

In [76]:
# Define a uniform distribution between 0 and 4, sample 10 values
uniform(loc=0, scale=4).rvs(10)

array([3.16138308, 2.17389022, 3.28027073, 1.0739343 , 3.65757664,
       1.60814535, 2.12086307, 0.66498063, 0.14017599, 0.36701938])

In [77]:
# View best hyperparameters
print('Best Penalty:', best_model.best_estimator_.get_params()['penalty'])
print('Best C:', best_model.best_estimator_.get_params()['C'])

Best Penalty: l2
Best C: 0.3712032345629517


In [78]:
# Predict target vector
best_model.predict(features)

array([1, 0, 1, 0, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0,
       1, 0, 1, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 1,
       1, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1, 0, 0, 0,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       1, 1, 0, 0, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 1, 1,
       1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1, 1,
       1, 1, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 1,
       0, 1, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0,
       1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 1, 1, 1, 1, 0, 0, 0,
       0, 1, 0, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 0, 0,
       0, 0, 1, 1, 0, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 1, 0, 0,
       1, 0, 0, 0, 0, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1,

# 12.3 Selecting Best Models from Multiple Learning Algorithms

In [79]:
# Problem
# You want to select the best model by searching over a range of 
# learning algorithms and their respective hyperparameters.

In [80]:
# Solution
# Create a dictionary of candidate learning algorithms and their hyperparameters:

In [81]:
# Load libraries
import numpy as np
from sklearn import datasets
from sklearn.linear_model import LogisticRegression
from sklearn.ensemble import RandomForestClassifier
from sklearn.model_selection import GridSearchCV
from sklearn.pipeline import Pipeline

In [82]:
# Set random seed
np.random.seed(0)

In [83]:
df.head(5)

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [84]:
features

array([[  6.   , 148.   ,  72.   , ...,  33.6  ,   0.627,  50.   ],
       [  1.   ,  85.   ,  66.   , ...,  26.6  ,   0.351,  31.   ],
       [  8.   , 183.   ,  64.   , ...,  23.3  ,   0.672,  32.   ],
       ...,
       [  5.   , 121.   ,  72.   , ...,  26.2  ,   0.245,  30.   ],
       [  1.   , 126.   ,  60.   , ...,  30.1  ,   0.349,  47.   ],
       [  1.   ,  93.   ,  70.   , ...,  30.4  ,   0.315,  23.   ]])

In [85]:
target

array([[1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
    

In [86]:
# Create a pipeline
pipe = Pipeline([("classifier", RandomForestClassifier())])

In [87]:
# Create dictionary with candidate learning algorithms and their hyperparameters
search_space = [{"classifier": [LogisticRegression()],
                 "classifier__penalty": ['l1', 'l2'],
                 "classifier__C": np.logspace(0, 4, 10)},
                {"classifier": [RandomForestClassifier()],
                 "classifier__n_estimators": [10, 100, 1000],
                 "classifier__max_features": [1, 2, 3]}]

In [88]:
# Create grid search
gridsearch = GridSearchCV(pipe, search_space, cv=5, verbose=0)

In [89]:
# Fit grid search
best_model = gridsearch.fit(features, target)

c:\python38\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\python38\lib\site-packages\sklearn\linear_model\_logistic.py:444: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
c:\python38\lib\site-packages\sklearn\utils\validation.py:1111: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn

# Linear regression

In [92]:
# Fitting a Line
# Problem
# You want to train a model that represents a linear relationship between the feature and target vector.

# Solution
# Use a linear regression (in scikit-learn, LinearRegression):



In [93]:
import pandas as pd

df_2015 = pd.read_csv('2015.csv')

In [94]:
df_2015.head(5)

Country          Region  Happiness Rank  Happiness Score  \
0  Switzerland  Western Europe               1            7.587   
1      Iceland  Western Europe               2            7.561   
2      Denmark  Western Europe               3            7.527   
3       Norway  Western Europe               4            7.522   
4       Canada   North America               5            7.427   

   Standard Error  Economy (GDP per Capita)   Family  \
0         0.03411                   1.39651  1.34951   
1         0.04884                   1.30232  1.40223   
2         0.03328                   1.32548  1.36058   
3         0.03880                   1.45900  1.33095   
4         0.03553                   1.32629  1.32261   

   Health (Life Expectancy)  Freedom  Trust (Government Corruption)  \
0                   0.94143  0.66557                        0.41978   
1                   0.94784  0.62877                        0.14145   
2                   0.87464  0.64938                        0.48357   
3                   0.88521  0.66973                        0.36503   
4                   0.90563  0.63297                        0.32957   

   Generosity  Dystopia Residual  
0     0.29678            2.51738  
1     0.43630            2.70201  
2     0.34139            2.49204  
3     0.34699            2.46531  
4     0.45811            2.45176

In [99]:
df_2015['Country'] = pd.factorize(df_2015['Country'])[0]
df_2015.head(10)

Country  Region  Happiness Rank  Happiness Score  Standard Error  \
0        0       0               1            7.587         0.03411   
1        1       0               2            7.561         0.04884   
2        2       0               3            7.527         0.03328   
3        3       0               4            7.522         0.03880   
4        4       1               5            7.427         0.03553   
5        5       0               6            7.406         0.03140   
6        6       0               7            7.378         0.02799   
7        7       0               8            7.364         0.03157   
8        8       2               9            7.286         0.03371   
9        9       2              10            7.284         0.04083   

   Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                   1.39651  1.34951                   0.94143  0.66557   
1                   1.30232  1.40223                   0.94784  0.62877   
2                   1.32548  1.36058                   0.87464  0.64938   
3                   1.45900  1.33095                   0.88521  0.66973   
4                   1.32629  1.32261                   0.90563  0.63297   
5                   1.29025  1.31826                   0.88911  0.64169   
6                   1.32944  1.28017                   0.89284  0.61576   
7                   1.33171  1.28907                   0.91087  0.65980   
8                   1.25018  1.31967                   0.90837  0.63938   
9                   1.33358  1.30923                   0.93156  0.65124   

   Trust (Government Corruption)  Generosity  Dystopia Residual  
0                        0.41978     0.29678            2.51738  
1                        0.14145     0.43630            2.70201  
2                        0.48357     0.34139            2.49204  
3                        0.36503     0.34699            2.46531  
4                        0.32957     0.45811            2.45176  
5                        0.41372     0.23351            2.61955  
6                        0.31814     0.47610            2.46570  
7                        0.43844     0.36262            2.37119  
8                        0.42922     0.47501            2.26425  
9                        0.35637     0.43562            2.26646

In [98]:
df_2015['Region'] = pd.factorize(df_2015['Region'])[0]
df_2015.head(10)

Country  Region  Happiness Rank  Happiness Score  Standard Error  \
0        0       0               1            7.587         0.03411   
1        1       0               2            7.561         0.04884   
2        2       0               3            7.527         0.03328   
3        3       0               4            7.522         0.03880   
4        4       1               5            7.427         0.03553   
5        5       0               6            7.406         0.03140   
6        6       0               7            7.378         0.02799   
7        7       0               8            7.364         0.03157   
8        8       2               9            7.286         0.03371   
9        9       2              10            7.284         0.04083   

   Economy (GDP per Capita)   Family  Health (Life Expectancy)  Freedom  \
0                   1.39651  1.34951                   0.94143  0.66557   
1                   1.30232  1.40223                   0.94784  0.62877   
2                   1.32548  1.36058                   0.87464  0.64938   
3                   1.45900  1.33095                   0.88521  0.66973   
4                   1.32629  1.32261                   0.90563  0.63297   
5                   1.29025  1.31826                   0.88911  0.64169   
6                   1.32944  1.28017                   0.89284  0.61576   
7                   1.33171  1.28907                   0.91087  0.65980   
8                   1.25018  1.31967                   0.90837  0.63938   
9                   1.33358  1.30923                   0.93156  0.65124   

   Trust (Government Corruption)  Generosity  Dystopia Residual  
0                        0.41978     0.29678            2.51738  
1                        0.14145     0.43630            2.70201  
2                        0.48357     0.34139            2.49204  
3                        0.36503     0.34699            2.46531  
4                        0.32957     0.45811            2.45176  
5                        0.41372     0.23351            2.61955  
6                        0.31814     0.47610            2.46570  
7                        0.43844     0.36262            2.37119  
8                        0.42922     0.47501            2.26425  
9                        0.35637     0.43562            2.26646

In [100]:
df_2015.isna().sum().sum()

0

In [101]:
features = np.array(df_2015[['Country', 'Region', 'Happiness Rank', 'Happiness Score', 'Standard Error', 
                             'Economy (GDP per Capita)', 'Family', 'Health (Life Expectancy)', 'Freedom', 
                             'Trust (Government Corruption)', 'Generosity']])
features

array([[0.0000e+00, 0.0000e+00, 1.0000e+00, ..., 6.6557e-01, 4.1978e-01,
        2.9678e-01],
       [1.0000e+00, 0.0000e+00, 2.0000e+00, ..., 6.2877e-01, 1.4145e-01,
        4.3630e-01],
       [2.0000e+00, 0.0000e+00, 3.0000e+00, ..., 6.4938e-01, 4.8357e-01,
        3.4139e-01],
       ...,
       [1.5500e+02, 3.0000e+00, 1.5600e+02, ..., 1.5684e-01, 1.8906e-01,
        4.7179e-01],
       [1.5600e+02, 8.0000e+00, 1.5700e+02, ..., 1.1850e-01, 1.0062e-01,
        1.9727e-01],
       [1.5700e+02, 8.0000e+00, 1.5800e+02, ..., 3.6453e-01, 1.0731e-01,
        1.6681e-01]])

In [104]:
import numpy as np

In [105]:
target = np.array(df_2015[['Dystopia Residual']])
target

array([[2.51738],
       [2.70201],
       [2.49204],
       [2.46531],
       [2.45176],
       [2.61955],
       [2.4657 ],
       [2.37119],
       [2.26425],
       [2.26646],
       [3.08854],
       [3.17728],
       [2.5332 ],
       [3.60214],
       [2.51011],
       [3.26001],
       [1.96961],
       [1.9757 ],
       [2.41484],
       [2.24743],
       [1.96994],
       [2.47489],
       [3.19131],
       [1.88501],
       [2.84848],
       [2.11569],
       [2.67585],
       [1.55674],
       [2.21126],
       [2.836  ],
       [2.67782],
       [2.32142],
       [2.85737],
       [2.31945],
       [2.43872],
       [2.12367],
       [1.6488 ],
       [2.32323],
       [1.87634],
       [2.79094],
       [2.26882],
       [3.035  ],
       [2.74255],
       [2.23741],
       [2.24639],
       [1.68435],
       [2.21978],
       [2.53942],
       [1.73797],
       [2.02518],
       [2.82334],
       [3.10712],
       [2.18896],
       [2.24729],
       [1.61583],
       [2.

In [106]:
# Create linear regression
regression = LinearRegression()

In [107]:
# Fit the linear regression
model = regression.fit(features, target)

In [108]:
# View the intercept
model.intercept_

array([-0.00048819])

In [109]:
# View the feature coefficients
model.coef_

array([[ 4.04686267e-04, -2.06517993e-05, -4.01021708e-04,
         1.00009773e+00,  1.57702230e-04, -1.00009832e+00,
        -9.99938250e-01, -9.99913653e-01, -9.99600377e-01,
        -9.99976817e-01, -1.00008111e+00]])

In [113]:
target[0] # first actual target

array([2.51738])

In [114]:
# Predict the target value of the first observation
model.predict(features)[0]

array([2.51755661])

In [115]:
target[1] # second actual target

array([2.70201])

In [116]:
# Predict the target value of the second observation
model.predict(features)[1]

array([2.70221065])

In [11]:
# Python program to display the given integer in reverse manner
integerNumber = input("Enter your Integer: ")
list = []
for i in integerNumber: 
    list.append(i)
reverselist = list[::-1]
print(reverselist)

Enter your Integer:  12345


['5', '4', '3', '2', '1']


In [12]:
# Python program to display the given integer in reverse manner
list = input("Enter your Integer: ")

reverselist = list[::-1]
print(reverselist)

Enter your Integer:  12345


54321


In [3]:
# Python program to print the numbers from a given number n till 0

number = input("Enter the number: ")
integer = int(number)

for i in range(0, integer+1, 1):
    my_number = integer - i
    print(my_number)

Enter the number:  10


10
9
8
7
6
5
4
3
2
1
0


In [6]:
# Python program to find the factorial of a number.

number = input("Enter the number: ")
integerNumber = int(number)
product = 1
for i in range(1, integerNumber+1, 1):
    product = product * i
print(product)

Enter the number:  6


720


In [8]:
# Python program to generate the prime numbers from 1 to N

number_N = input("Enter the number: ")
integer_N = int(number_N)
prime_number = []

for i in range(2, integer_N+1, 1):  # List of integers to be used as divisors for the input integer N
    check = []
    for j in range(2, i, 1):
        remains = (i % j)
        check.append(remains)
    y = check.count(0)
    if y==0:
        prime_number.append(i)
                      
print("The prime from 1 to " + number_N + " are " + str(prime_number))

Enter the number:  200


The prime from 1 to 200 are [2, 3, 5, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53, 59, 61, 67, 71, 73, 79, 83, 89, 97, 101, 103, 107, 109, 113, 127, 131, 137, 139, 149, 151, 157, 163, 167, 173, 179, 181, 191, 193, 197, 199]
